config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root 'pages#home'

  resources :messages, :only => [:index, :create, :show]

  post 'profiles/:id/delete_image', to: 'profiles#delete_image'

  resources :profiles, :only => [:show, :edit, :update] do
    collection do
      get :search
      get :search_results
    end
  end
end

app/views/pages/home.html.erb
<div class="row">
  <div class="center-content home-signup col-sm-6 col-sm-offset-3">
   
    <% if current_customer %>
      <h2>Welcome <%= current_customer.username %>!</h2>
    <% else %>
      <h2>Register for free!</h2>

      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>

        <%= f.label :username %><br />
        <%= f.text_field :username, class: "form-control", autofocus: true %>

        <%= f.label :email %><br />
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :password %>
        <% if @validatable %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, class: "form-control", autocomplete: "off" %>

        <%= f.label :password_confirmation, "Confirm Password" %><br />
        <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "off" %>

        <%= f.submit "Sign up", class: "form-control btn btn-warning mt-10" %>
      <% end %>

      <div class="text-center mt-10 mb-10">
        <%= link_to "Log in", new_customer_session_path %>
      </div>
    <% end %>
  </div>
</div>  