config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root 'pages#home'

  resources :messages, :only => [:index, :create, :show]

  post 'profiles/:id/delete_image', to: 'profiles#delete_image'

  resources :profiles, :only => [:show, :edit, :update] do
    collection do
      get :search
      get :search_results
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wegotsingles</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper" id="<%= @background_image %>">
    <header class="container-fluid primary">
      <div class="row">
        <div class="col-sm-3">
          <%= link_to image_tag('logo.png'), root_path %>
        </div>

        <div class="col-sm-2 col-sm-offset-7">
          <ul>
            <% if current_customer %>
              <li><%= link_to 'Sign Out', destroy_customer_session_path, method: :delete, class: "btn btn-info" %></li>
            <% else %>
              <li><%= link_to 'Sign In', new_customer_session_path, class: "btn btn-info" %></li>
              <li><%= link_to 'Register', new_customer_registration_path, class: "btn btn-warning" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>

    <% if current_customer %>
      <%= render "shared/nav.html.erb" %>
    <% end %>

    <div class="flash-messages">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <main>
      <div class="container content">
        <div class="clearfix"></div>
        <%= yield %>
      </div>
    </main>

    <footer class="primary">
      &#169; 2016 We Got Coders
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </div>

</body>
</html>